config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                skills GET    /skills(.:format)                                                                        skills#index
#                                       POST   /skills(.:format)                                                                        skills#create
#                             new_skill GET    /skills/new(.:format)                                                                    skills#new
#                            edit_skill GET    /skills/:id/edit(.:format)                                                               skills#edit
#                                 skill GET    /skills/:id(.:format)                                                                    skills#show
#                                       PATCH  /skills/:id(.:format)                                                                    skills#update
#                                       PUT    /skills/:id(.:format)                                                                    skills#update
#                                       DELETE /skills/:id(.:format)                                                                    skills#destroy
#                                 login GET    /login(.:format)                                                                         sessions#new
#                                       POST   /login(.:format)                                                                         sessions#create
#                                logout DELETE /logout(.:format)                                                                        sessions#destroy
#                 skill_edit_admin_user GET    /admin/users/:id/skill_edit(.:format)                                                    admin/users#skill_edit
#               skill_update_admin_user POST   /admin/users/:id/skill_update(.:format)                                                  admin/users#skill_update
#     skill_proficiency_edit_admin_user GET    /admin/users/:id/skill_proficiency_edit(.:format)                                        admin/users#skill_proficiency_edit
#   skill_proficiency_update_admin_user POST   /admin/users/:id/skill_proficiency_update(.:format)                                      admin/users#skill_proficiency_update
#                           admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                                       POST   /admin/users(.:format)                                                                   admin/users#create
#                        new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#                       edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                            admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                                       PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                                       PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                                       DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#                                  root GET    /                                                                                        tasks#index
#                      confirm_new_task POST   /tasks/new/confirm(.:format)                                                             tasks#confirm_new
#                          import_tasks POST   /tasks/import(.:format)                                                                  tasks#import
#                                 tasks GET    /tasks(.:format)                                                                         tasks#index
#                                       POST   /tasks(.:format)                                                                         tasks#create
#                              new_task GET    /tasks/new(.:format)                                                                     tasks#new
#                             edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
#                                  task GET    /tasks/:id(.:format)                                                                     tasks#show
#                                       PATCH  /tasks/:id(.:format)                                                                     tasks#update
#                                       PUT    /tasks/:id(.:format)                                                                     tasks#update
#                                       DELETE /tasks/:id(.:format)                                                                     tasks#destroy
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  
  resources :skills
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # match '/login', to: 'sessions#create', via: [:post, :patch, :put]
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users do
      get :skill_edit, on: :member
      post :skill_update, on: :member
      get :skill_proficiency_edit, on: :member
      post :skill_proficiency_update, on: :member
    end
  end

  root to: 'tasks#index'
  # get 'tasks/index'
  # get 'tasks/show'
  # get 'tasks/new'
  # get 'tasks/edit'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
    get :plan, on: :collection
    post :check_plan, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string(30)       not null
#  special     :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_name     (name)
#  index_tasks_on_user_id  (user_id)
#
class Task < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validates :name, uniqueness: true, uniqueness: { scope: :user_id }
  validate :validate_name_not_including_comma

  belongs_to :user

  scope :recent, ->{ order(created_at: :desc) }
  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    %w[name created_at]
  end
  
  def self.ransackable_associations(auth_object = nil)
    %w[user]
  end

  def self.csv_attributes
    ["name", "description", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map{|attr| task.send(attr) }
      end
    end
  end

  def self.import(file)
    if file
      CSV.foreach(file.path, headers: true) do |row|
        task = new
        task.attributes = row.to_hash.slice(*csv_attributes)
        task.save!
      end
      true
    else
      false
    end
  end

  private
  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  Payjp.api_key = ENV.fetch('PAYJP_PRIVATE_KEY')
  
  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.csv { send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def import
    if current_user.tasks.import(params[:file])
      redirect_to tasks_url, notice: "タスクを追加しました"
    else
      redirect_to tasks_url, notice: "CSVファイルを選択してください"
    end
  end

  def plan
    @user = current_user
    @card = Card.new
    if @user.subscription
      subscription = Payjp::Subscription.retrieve(@user.subscription)
      @plan_name = subscription[:plan][:name]
    end
  end

  def check_plan
    @user = current_user

    # card_params = params.require(:card).permit(:number, :month, :year, :cvc, :name, :plan)
    # @card = Card.new(card_params)
    # if @card.save(current_user, params["payjp-token"])
    #   return redirect_to tasks_url, notice: "【プレミアムユーザー】#{User::PLANS[plan]}プランに申し込みました。"
    # else
    #   return render :plan
    # end

    plan = params.require(:user).permit(:plan)[:plan]

    plan_remote_id = User::PLANS_REMOTE[plan]

    customer = Payjp::Customer.create(card: params["payjp-token"])
    @user.customer = customer[:id]

    # charge = Payjp::Charge.create(
    #   :amount => 500,
    #   :card => params["payjp-token"], // テンポラリトークン
    #   :currency => 'jpy',
    # )
    # plan = Payjp::Plan.create(
    #   amount:   500,
    #   interval: 'month',
    #   currency: 'jpy'
    # )
    # plan[:id]

    subscription = Payjp::Subscription.create(
      customer: customer[:id],
      plan:     plan_remote_id,
    )
    @user.subscription = subscription[:id]
    @user.premium = true
    if @user.save
      redirect_to tasks_url, notice: "【プレミアムユーザー】#{User::PLANS[plan]}プランに申し込みました。"
    else
      render :plan
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def create
    @task = current_user.tasks.new(task_params)
    
    if params[:back].present?
      render :new
      return
    end

    if @task.save
      TaskMailer.creation_email(@task, current_user).deliver_now
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    # redirect_to tasks_url, notice: "タスク「#{@task.name}」を削除しました。"
    head :no_content
  end

  private
  def task_params
    if current_user.premium?
      params.require(:task).permit(:name, :description, :special, :image)
    else
      params.require(:task).permit(:name, :description, :image)
    end
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true, url: url do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  -if current_user.premium?
    .form-check
      = f.label :special, class: 'form-check-label' do
        = f.check_box :special, class: 'form-check-input'
        | 目立たせる

  = f.submit nil, class: 'btn btn-primary', data: { disable_with: "送信中..." }

app/views/tasks/_td.html.slim
td= link_to task.name, task
td=task.special? ? 'あり' : 'なし'
td= task.created_at
td
  = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3', data: { disable_with: "遷移中..." }

  = link_to '削除', task, method: :delete, remote: true, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger delete'

app/views/tasks/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th= Task.human_attribute_name(:name)
        td= @task.name
        = f.hidden_field :name
      tr
        th= Task.human_attribute_name(:description)
        td= simple_format(@task.description)
        = f.hidden_field :description
      -if current_user.premium?
        tr
          th= Task.human_attribute_name(:special)
          td= @task.special? ? 'あり' : 'なし'
          = f.hidden_field :special

  = f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3', data: {disable_with: "遷移中..."}
  = f.submit '登録', class: 'btn btn-primary', data: {disable_with: "登録中..."}

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task, url: task_path(@task) }

app/views/tasks/index.html.slim
h1
  | タスク一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称(含む)', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日時(以上)', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group.row
    = f.label :user_email_cont, 'ユーザのメール(含む)', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :user_email_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary', data: { disable_with: "検索中..." }

=link_to '新規登録', new_task_path, class: 'btn btn-primary mr-3'
=link_to '有料プラン', plan_tasks_path, class: 'btn btn-primary'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

.mb-3.mt-3
  table.table.table-hover
    thead.thead-default
      tr
        th= sort_link(@q, :name, default_order: :desc)
        th= Task.human_attribute_name(:spcial)
        th= Task.human_attribute_name(:created_at)
        th
    tbody
      - @tasks.each do |task|
        -if task.special?
          tr id="task-#{task.id}" class="pink"
            = render partial: 'td', locals: { task: task }
        -else
          tr id="task-#{task.id}"
            = render partial: 'td', locals: { task: task }
= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file
  = submit_tag "インポート", class: 'btn btn-primary'

app/views/tasks/new.html.slim
h1
  | タスクの新規登録
.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task, url: confirm_new_task_path }

app/views/tasks/plan.html.slim
h1 プレミアムユーザープラン申し込み
.row.justify-content-center
  .col-md-8.mt-5
    -if current_user.subscription
      p= "【プレミアムユーザー】#{@plan_name}に入っています。"
      = link_to '一覧へ戻る', tasks_path, class: 'btn btn-primary'
    -else
      p プレミアムユーザーになるとタスクを目立たせる機能が使えるようになります。カード番号4242 4242 4242 4242を入力するとお試しで登録できます。
      = form_with model:@user, url:check_plan_tasks_path, method: :post do |f|
        -User::PLANS.each do |key, val|
          .form-check.mb-2
            = f.radio_button :plan, key, checked: true, id: "plan_#{key}", class: "form-check-input"
            = f.label :plan, "#{val}プラン", for: "plan_#{key}", class: "form-check-label"
        script src="https://checkout.pay.jp/" class="payjp-button" type="text/javascript" data-key="#{ENV.fetch('PAYJP_KEY')}"


/ .row.justify-content-center
/   .col-md-8
/     - if @card.errors.present?
/       ul#error_explanation
/       - @card.errors.full_messages.each do |message|
/         li= message
/     = form_with model:@card, local: true, url:check_plan_tasks_path, method: :post, class: "form" do |f|
/       .form-row
/         .form-group.col-sm-12
/           = f.label :number
/           = f.text_field :number, class: 'form-control', placeholder: '4242424242424242', inputmode: "numeric"
/       .form-row
/         .form-group.col-sm-3
/           = f.label :month
/           = f.text_field :month, class: 'form-control', placeholder: '12', inputmode: "numeric"
/         .form-group.col-sm-3
/           = f.label :year
/           = f.text_field :year, class: 'form-control', placeholder: '2020', inputmode: "numeric"
/         .form-group.col-sm-6.row
/           = f.label :cvc, class: "ml-3 "
/           = link_to asset_url('creditcards/type_01.png'), target: "_blank", class: "col-sm-2"
/             i.fa.fa-question-circle"
/           = f.text_field :cvc, class: 'form-control ml-3', placeholder: '***', inputmode: "numeric"
/       .form-row
/         .form-group.col-sm-12
/           = f.label :name
/           = f.text_field :name, class: 'form-control', placeholder: 'SATSHI NAKAMOTO'
/       -Card::PLANS.each do |key, val|
/         .form-check.mb-2
/           = f.radio_button :plan, key, checked: true, id: "plan_#{key}", class: "form-check-input"
/           = f.label :plan, "#{val}プラン", for: "plan_#{key}", class: "form-check-label"
/       = f.submit "プランを申し込む", class: 'btn btn-primary mt-3', data: { disable_with: "送信中..." }

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:special)
      td= @task.special? ? 'あり' : 'なし'
    tr
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Task.human_attribute_name(:image)
      /td= image_tag @task.image.variant(combine_options:{resize:"640x640^",crop:"640x640+0+0",gravity: :center}).processed if @task.image.attached?
      td= image_tag @task.image if @task.image.attached?
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'