config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                skills GET    /skills(.:format)                                                                        skills#index
#                                       POST   /skills(.:format)                                                                        skills#create
#                             new_skill GET    /skills/new(.:format)                                                                    skills#new
#                            edit_skill GET    /skills/:id/edit(.:format)                                                               skills#edit
#                                 skill GET    /skills/:id(.:format)                                                                    skills#show
#                                       PATCH  /skills/:id(.:format)                                                                    skills#update
#                                       PUT    /skills/:id(.:format)                                                                    skills#update
#                                       DELETE /skills/:id(.:format)                                                                    skills#destroy
#                                 login GET    /login(.:format)                                                                         sessions#new
#                                       POST   /login(.:format)                                                                         sessions#create
#                                logout DELETE /logout(.:format)                                                                        sessions#destroy
#                 skill_edit_admin_user GET    /admin/users/:id/skill_edit(.:format)                                                    admin/users#skill_edit
#               skill_update_admin_user POST   /admin/users/:id/skill_update(.:format)                                                  admin/users#skill_update
#     skill_proficiency_edit_admin_user GET    /admin/users/:id/skill_proficiency_edit(.:format)                                        admin/users#skill_proficiency_edit
#   skill_proficiency_update_admin_user POST   /admin/users/:id/skill_proficiency_update(.:format)                                      admin/users#skill_proficiency_update
#                           admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                                       POST   /admin/users(.:format)                                                                   admin/users#create
#                        new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#                       edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                            admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                                       PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                                       PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                                       DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#                                  root GET    /                                                                                        tasks#index
#                      confirm_new_task POST   /tasks/new/confirm(.:format)                                                             tasks#confirm_new
#                          import_tasks POST   /tasks/import(.:format)                                                                  tasks#import
#                                 tasks GET    /tasks(.:format)                                                                         tasks#index
#                                       POST   /tasks(.:format)                                                                         tasks#create
#                              new_task GET    /tasks/new(.:format)                                                                     tasks#new
#                             edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
#                                  task GET    /tasks/:id(.:format)                                                                     tasks#show
#                                       PATCH  /tasks/:id(.:format)                                                                     tasks#update
#                                       PUT    /tasks/:id(.:format)                                                                     tasks#update
#                                       DELETE /tasks/:id(.:format)                                                                     tasks#destroy
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  
  resources :skills
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # match '/login', to: 'sessions#create', via: [:post, :patch, :put]
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users do
      get :skill_edit, on: :member
      post :skill_update, on: :member
      get :skill_proficiency_edit, on: :member
      post :skill_proficiency_update, on: :member
    end
  end

  root to: 'tasks#index'
  # get 'tasks/index'
  # get 'tasks/show'
  # get 'tasks/new'
  # get 'tasks/edit'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
    get :plan, on: :collection
    post :check_plan, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  admin           :boolean          default(FALSE), not null
#  customer        :string
#  deleted_at      :datetime
#  email           :string           not null
#  locale          :string           default("ja"), not null
#  name            :string           not null
#  password_digest :string           not null
#  premium         :boolean          default(FALSE), not null
#  skill_names     :string
#  subscription    :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_deleted_at   (deleted_at)
#  index_users_on_email        (email) UNIQUE
#  index_users_on_skill_names  (skill_names)
#
class User < ApplicationRecord
  attr_accessor:plan

  has_secure_password
  # acts_as_paranoid
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks, dependent: :destroy
  has_many :skillsUsers, dependent: :destroy
  has_many :skills, through: :skillsUsers

  PLANS = {"1"=>"月次", "2"=>"年次"}
  PLANS_REMOTE = {"1"=>'pln_6c04034830aa5ad616c5447b1936', "2"=>'pln_3016b66e77175593f980c57b7f90'}

  def update_skill_names!(skill_ids_ary)
    skill_ids_ary.map!(&:id) if skill_ids_ary.first.is_a?(Skill) 

    ActiveRecord::Base.transaction do
      self.skill_ids = skill_ids_ary
      self.skill_names = skills.map(&:name).sort_by{|v|v}.join(',')
      save!
    end
  end

  def set_proficiency!(hash)
    ActiveRecord::Base.transaction do
      hash.each do |id, proficiency|
        skillsUser = self.skillsUsers.find(id)
        skillsUser.proficiency = proficiency
        skillsUser.save!
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[id name email skill_names]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[skills]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def skill_proficiency_edit
    @user = User.find(params[:id])
    @skillsUsers = @user.skillsUsers.includes(:skill)
  end

  def skill_proficiency_update
    @user = User.find(params[:id])
    @user.set_proficiency!(params[:proficiency])
    redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
  end

  def skill_edit
    @user = User.find(params[:id])
    @skillhash_by_kind_name = Skill.skillhash_by_kind_name
    @users_skills = @user.skills.to_ary
  end

  def skill_update
    @user = User.find(params[:id])
    @user.update_skill_names!(params[:skills])
    redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  def index
    if params[:q]
      params[:q]["skills_name_cont_any"] = parameter_conversion(params[:q]["skills_name_cont_any"])
      params[:q]["skills_name_in"] = parameter_conversion(params[:q]["skills_name_in"])
      params[:q]["skill_names_cont"] = parameter_conversion(params[:q]["skill_names_cont"]).join(',')
      
    end

    # SQL文を生で書いても絞り込む方法は無い
    # OR検索でしか件数が取れない
    # User.find_by_sql("SELECT users.* FROM users WHERE id in (
    #   SELECT skills_users.user_id FROM skills_users INNER JOIN skills ON skills_users.skill_id = skills.id WHERE skills.name = 'XD' OR skills.name = 'PHP'
    # );").size

    # User.find_by_sql("SELECT DISTINCT users.* FROM users WHERE users.id in (SELECT DISTINCT skills_users.user_id FROM skills_users WHERE skills_users.skill_id in (SELECT skills.id FROM skills WHERE skills.name in ('XD', 'PHP')))").count
    
    # OR 検索したものをコレクションをまわして絞り込む方法
    # 微妙なので没
    if params[:q] && params[:q]["skills_name_in"]
      @q = User.ransack(params[:q])
      users = 
        @q.result(distinct: true).includes([:skillsUsers, :skills]).map do |user|
          skill_names = user.skills.map(&:name)
          ret =
            params[:q]["skills_name_in"].all? do |w|
              skill_names.include?(w)
            end
          user if ret
        end.compact
      params[:q]["id_eq_any"] = users.map(&:id)
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).includes([:skillsUsers, :skills]).page(params[:page]).per(10)
      # @users = @q.result(distinct: true).page(params[:page]).per(10)
    else 
      @q = User.ransack(params[:q])
      # @users = @q.result(distinct: true).includes([:skillsUsers, :skills]).page(params[:page]).per(10)
      @users = @q.result(distinct: true).page(params[:page]).per(10)
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :locale, :premium, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

  def parameter_conversion(params)
    if params
      params&.split(/[\s 　,]/)&.sort_by{|v|v}.map do |v|
        if v.blank?
          nil
        else
          v
        end
      end.compact
    end
  end
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :locale, 'ロケール'
    = f.text_field :locale, class: 'form-control'
  .form-check
    = f.label :premium, class: 'form-check-label' do
      = f.check_box :premium, class: 'form-check-input'
      | プレミアム
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/destroy.js.erb
document.querySelector('#user-<%= @user.id %>').style.display = 'none';

var message = document.createElement('p');
message.innerText = 'タスク「<%= @user.name %>」を削除しました。残りのタスクは<%= User.count %>件です。';
document.querySelector('table').insertAdjacentElement('beforebegin', message);

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= search_form_for @q, url: admin_users_path, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名前(含む)', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :skills_name_cont_any, 'スキル名(含む)orひとつでも含む', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :skills_name_cont_any, class: 'form-control'
  .form-group.row
    = f.label :skills_name_in, 'スキル名in全て含むもの', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :skills_name_in, class: 'form-control'
  .form-group.row
    = f.label :skill_names_cont, 'スキル名(含む)and検索用カラム', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :skill_names_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary', data: { disable_with: "検索中..." }



= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
  = paginate @users
  = page_entries_info @users

.mb-3.mt-3
  table.table.table-hover
    thead.thead-default
      tr
        th= sort_link(@q, :name, default_order: :desc)
        th= User.human_attribute_name(:email)
        th= User.human_attribute_name(:locale)
        th= User.human_attribute_name(:premium)
        th= User.human_attribute_name(:admin)
        th= User.human_attribute_name(:skill_names)
        th= User.human_attribute_name(:created_at)
        th= User.human_attribute_name(:updated_at)
        th
    tbody
    - @users.each do |user|
      tr id="user-#{user.id}"
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.locale
        td= user.premium? ? 'あり' : 'なし'
        td= user.admin? ? 'あり' : 'なし'
        td= user.skill_names
        td= user.created_at
        td= user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'

          = link_to '削除', admin_user_path(user), method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:locale)
      td= @user.locale
    tr
      th= User.human_attribute_name(:premium)
      td= @user.premium? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:skill_names)
      td= td= @user.skill_names
    tr
      th= User.human_attribute_name(:customer)
      td= td= @user.customer
    tr
      th= User.human_attribute_name(:subscription)
      td= td= @user.subscription
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at



= link_to 'スキル設定', skill_edit_admin_user_path(@user), class: 'btn btn-primary mr-3', data: { disable_with: "遷移中..." }
= link_to 'スキル習熟度設定', skill_proficiency_edit_admin_user_path(@user), class: 'btn btn-primary mr-3', data: { disable_with: "遷移中..." }
= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/skill_edit.html.erb
<%= form_tag(controller: "users",action: "skill_update", method: "post") do %>
  <div class="form-group mt-5">
    <label for="skills">スキル選択:</label>
    <select name="skills[]" id="skills" class="form-control" multiple size="6">
    <% @skillhash_by_kind_name.each do |key, skills| %>
      <optgroup label="<%=key%>">
      <% skills.each do |skill|%>
        <option value="<%= skill.id %>" <%=@users_skills.include?(skill) ? "selected" : "" %>>
          <%= skill.name %>
        </option>
      <%end%>
      </optgroup>
    <% end %>
    </select>
  </div>

  <%= submit_tag "スキル更新", class: 'btn btn-primary' %>
<% end %>

<div class="check_area">
<%= form_tag(controller: "users",action: "skill_update", method: "post") do %>
  <% @skillhash_by_kind_name.each do |key, skills| %>
  <fieldset class="form-group mt-5">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0"><%=key%></legend>
      <div class="col-sm-10">
        <% skills.each do |skill|%>
          <div class="form-check">
            <label class="form-check-label" for="skill_<%=skill.id%>">
              <input type="checkbox" name="skills[]" id="skill_<%=skill.id%>" value="<%=skill.id%>" <%=@users_skills.include?(skill) ? "checked" : "" %>><%=skill.name%>
            </label>
          </div>
        <%end%>
      </div>
    </div>
  </fieldset>
  <% end %>
  <%= submit_tag "スキル更新", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/admin/users/skill_proficiency_edit.html.erb
<%= form_tag(controller: "users",action: "skill_proficiency_update", method: "post") do %>
  <% @skillsUsers.each do |skillsUser| %>
  <fieldset class="form-group mt-5">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0"><%=skillsUser.skill.name%></legend>
      <div class="col-sm-10">
        <%= label_tag "proficiency[#{skillsUser.id}]", '習熟度'%>
        <%= range_field_tag "proficiency[#{skillsUser.id}]", skillsUser.proficiency, in: 1..100, step: 1, class: 'form-control-range', list: "tlist__#{skillsUser.id}"%>
    　　　<datalist id="tlist__<%=skillsUser.id%>">
  　　　　　　<option value="1"></option>
  　　　　　　<option value="10"></option>
  　　　　　　<option value="20"></option>
  　　　　　　<option value="30"></option>
  　　　　　　<option value="40"></option>
  　　　　　　<option value="50"></option>
  　　　　　　<option value="60"></option>
  　　　　　　<option value="70"></option>
  　　　　　　<option value="80"></option>
  　　　　　　<option value="90"></option>
  　　　　　　<option value="100"></option>
    　　　</datalist>
      </div>
    </div>
  </fieldset>
  <% end %>
  <%= submit_tag "スキル更新", class: 'btn btn-primary' %>
<% end %>